apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchdog
  namespace: watchdog
  labels:
    app.kubernetes.io/name: watchdog
    app.kubernetes.io/part-of: grip-watchdog
automountServiceAccountToken: false
